doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Application\Migrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
    storage:
        table_storage:
            table_name: 'migration_versions'
