twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        ga_enabled: "%env(bool:GA_ENABLED)%"
        global_menu_prefix: "%env(string:AFUP_GLOBAL_MENU_PREFIX)%"
when@test:
    twig:
        strict_variables: true
