services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $minResult: "%min_result%"

    _instanceof:
        Afup\Barometre\Report\ReportInterface:
            tags: ['barometre.report']

        Afup\Barometre\Filter\FilterInterface:
            tags: ['barometre.filter']

        Afup\BarometreBundle\Enums\EnumsInterface:
            tags: ['barometre.enums']

    Afup\Barometre\:
        resource: '../../src/Afup/Barometre/*'

    Afup\BarometreBundle\:
        resource: '../../src/Afup/BarometreBundle/*'

    Afup\BarometreBundle\Controller\:
        resource: '../../src/Afup/BarometreBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Afup\Barometre\Filter\FilterCollection:
        arguments: [!tagged barometre.filter]
    Afup\Barometre\Report\ReportCollection:
        arguments: [!tagged barometre.report]
    Afup\BarometreBundle\Enums\EnumsCollection:
        arguments: [!tagged barometre.enums]

    Afup\BarometreBundle\Campaign\ResponseFactory:
        arguments:
            $numberFormatter: '@number_formatter'

    Afup\Barometre\ReportManager:
        shared: false
        arguments:
            $form: '@afup.barometre.filter_form'
